name: Keploy API Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  keploy-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask App in Background
        run: |
          nohup python run.py &
          sleep 10

      - name: Run Keploy Tests
        run: |
          curl -s https://raw.githubusercontent.com/keploy/keploy/main/install.sh | bash
          ./keploy test -c "curl http://localhost:5000/api/regions"